<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ApiError, get } from '../api'
const router=useRouter(), data=ref<any>(), loading=ref(true), error=ref('')
const money=(n:number)=>`¥${Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:2})}`
const serviceLabels:Record<string,string>={BIDDING:'招标',COST:'造价',SUPERVISION:'监理',OTHER:'其他'}
async function load(){loading.value=true;error.value='';try{data.value=await get('/dashboard')}catch(e){error.value=e instanceof ApiError?e.message:'驾驶舱加载失败'}finally{loading.value=false}}
onMounted(load)
</script>
<template><div v-if="loading" class="empty"><p>正在加载驾驶舱…</p></div><div v-else-if="error" class="empty"><h3>暂时无法加载驾驶舱</h3><p class="error">{{error}}</p><button class="button secondary" @click="load">重试</button></div><template v-else-if="data"><div class="heading"><div><h1 class="title">驾驶舱</h1><p class="subtitle">公司现在最值得关注的事情</p></div><div class="eyebrow">{{new Date().toLocaleDateString('zh-CN')}}</div></div><section class="kpis"><button class="kpi" @click="router.push('/projects?status=ACTIVE')"><div class="kpi-num">{{data.activeCount}}</div><div class="kpi-label">在办项目</div><div class="kpi-meta">查看当前项目</div></button><button class="kpi" @click="router.push('/projects?hasRisk=true')"><div class="kpi-num">{{data.attentionCount}}</div><div class="kpi-label">需要关注</div><div class="kpi-meta">风险规则实时计算</div></button><button class="kpi" @click="router.push('/finance')"><div class="kpi-num">{{money(data.receivableAmount)}}</div><div class="kpi-label">当前应收</div><div class="kpi-meta">合同额 - 已回款</div></button><button class="kpi" @click="router.push('/finance')"><div class="kpi-num">{{money(data.monthPaymentAmount)}}</div><div class="kpi-label">本月回款</div><div class="kpi-meta">实际回款记录</div></button></section><div class="line"/><section><div class="heading"><h2 class="section-title">需要关注</h2><RouterLink class="subtitle" to="/projects?hasRisk=true">查看全部 ↗</RouterLink></div><div v-if="data.risks.length" class="list"><RouterLink v-for="(risk,i) in data.risks" :key="`${risk.projectId}-${risk.reason}`" :to="`/projects/${risk.projectId}`" class="list-row"><b :style="{color:risk.level==='danger'?'var(--danger)':'var(--warning)'}">{{String(Number(i)+1).padStart(2,'0')}}</b><span>{{risk.projectName}}</span><span class="subtitle">{{risk.reason}}</span><span>{{risk.owner}}</span><span class="arrow">→</span></RouterLink></div><div v-else class="empty"><h3>当前没有需要特别关注的项目。</h3><p>所有在办项目都在规则范围内。</p></div></section><section class="split" style="margin-top:40px"><section><h2 class="section-title">未来 14 天</h2><div class="list"><RouterLink v-for="m in data.upcoming" :key="m.id" :to="`/projects/${m.projectId}`" class="list-row"><span class="eyebrow">{{m.plannedDate?.slice(5).replace('-','.')}}</span><span>{{m.projectName}} / {{m.name}}</span><span class="arrow">→</span></RouterLink><p v-if="!data.upcoming.length" class="subtitle">未来 14 天没有未完成关键节点。</p></div></section><section><h2 class="section-title">最近在办项目</h2><div class="list"><RouterLink v-for="p in data.recentProjects" :key="p.id" :to="`/projects/${p.id}`" class="list-row"><span>{{p.name}}</span><span class="subtitle">{{p.services.map((s:any)=>serviceLabels[s.serviceType]).join(' / ')}}</span><span class="arrow">→</span></RouterLink></div></section></section></template></template>
