<script setup lang="ts">
import { ref } from 'vue'
import { ApiError, post, session } from '../api'
const columns=['项目编号','项目名称*','客户*','年份*','服务类型*','负责人','状态*','开始日期','计划完成日期','实际完成日期','项目/采购标的金额','备注']
const preview=ref<{id:string;total:number;validCount:number;duplicateCount:number;errors:Array<{row:number;message:string}>;done?:boolean;imported?:number}>(), error=ref(''), loading=ref(false)
function download(){const csv='\ufeff'+columns.join(',')+'\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='历史项目导入模板.csv';anchor.click();URL.revokeObjectURL(url)}
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>10*1024*1024){error.value='文件不能超过 10 MB';return}error.value='';loading.value=true;try{const form=new FormData();form.append('file',file);const response=await fetch('/api/v1/imports/history/preview',{method:'POST',credentials:'include',body:form});const body=await response.json().catch(()=>({}));if(!response.ok)throw new ApiError(response.status,body.message||'预检失败');preview.value=body}catch(e){error.value=e instanceof Error?e.message:'预检失败'}finally{loading.value=false}}
async function confirm(){if(!preview.value)return;error.value='';loading.value=true;try{const result=await post<{created:number}>(`/imports/history/${preview.value.id}/confirm`);preview.value={...preview.value,imported:result.created,done:true}}catch(e){error.value=e instanceof Error?e.message:'导入失败'}finally{loading.value=false}}
</script>
<template><div style="max-width:850px"><h1 class="title">导入历史项目</h1><p class="subtitle">导入会在提交前进行服务端校验；原始文件保存到私有对象存储。</p><section v-if="session.isDemo" class="empty"><h3>演示账户不可导入</h3><p>注册正式账户后即可导入独立业务数据。</p></section><template v-else><div class="tabs"><button class="tab" :class="{active:!preview}">01 下载模板</button><button class="tab" :class="{active:preview&&!preview.done}">02 上传并检查</button><button class="tab" :class="{active:preview?.done}">03 确认导入</button></div><section v-if="!preview" class="empty" style="margin-top:38px"><i>↓</i><h3>下载模板并上传 Excel</h3><p>仅支持 .xlsx/.xls，单次最多 5,000 行、10 MB。</p><button class="button secondary" @click="download">下载模板</button><label class="button primary" style="margin-left:10px">{{loading?'检查中…':'选择 Excel 文件'}}<input type="file" accept=".xlsx,.xls" hidden :disabled="loading" @change="upload"/></label></section><section v-else class="form-section"><div class="kpis" style="margin-top:0"><div class="kpi"><div class="kpi-num">{{preview.total}}</div><div class="kpi-label">读取行数</div></div><div class="kpi"><div class="kpi-num">{{preview.validCount}}</div><div class="kpi-label">准备新增</div></div><div class="kpi"><div class="kpi-num">{{preview.duplicateCount}}</div><div class="kpi-label">可能重复</div></div><div class="kpi"><div class="kpi-num">{{preview.errors.length}}</div><div class="kpi-label">需要修改</div></div></div><div v-if="preview.errors.length" class="list" style="margin-top:24px"><div v-for="e in preview.errors" :key="`${e.row}-${e.message}`" class="list-row"><b>第 {{e.row}} 行</b><span class="error">{{e.message}}</span></div></div><p v-if="preview.done" class="success">已成功导入 {{preview.imported}} 个项目。</p><div class="actions"><button class="button secondary" :disabled="loading" @click="preview=undefined">重新上传</button><button class="button primary" :disabled="loading||preview.errors.length>0||preview.done" @click="confirm">{{preview.done?'导入已完成':`确认导入 ${preview.validCount} 个项目 →`}}</button></div></section></template><p v-if="error" class="error" role="alert">{{error}}</p></div></template>
