<script setup lang="ts">
import { onBeforeUnmount,onMounted,ref,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ApiError,get,session } from '../api'
import EmptyState from '../components/EmptyState.vue'
import RiskTag from '../components/RiskTag.vue'
const route=useRoute(), router=useRouter(), projects=ref<any[]>([]), q=ref(String(route.query.q||'')), status=ref(String(route.query.status||'ACTIVE')), loading=ref(false), error=ref('')
const labels:Record<string,string>={BIDDING:'招标代理',COST:'造价/预结算',SUPERVISION:'监理',OTHER:'其他'}
let timer: ReturnType<typeof setTimeout>|undefined, sequence=0
const service=(p:any)=>p.services.map((s:any)=>labels[s.serviceType]||'其他').join(' / ')
const next=(p:any)=>p.milestones.filter((m:any)=>!m.actualDate).sort((a:any,b:any)=>String(a.plannedDate).localeCompare(String(b.plannedDate)))[0]
async function load(){const current=++sequence;loading.value=true;error.value='';try{const params=new URLSearchParams();if(status.value!=='ALL')params.set('status',status.value);if(q.value.trim())params.set('q',q.value.trim());if(route.query.hasRisk==='true')params.set('hasRisk','true');const result=await get<any[]>(`/projects?${params}`);if(current===sequence)projects.value=result}catch(e){if(current===sequence)error.value=e instanceof ApiError?e.message:'项目列表加载失败'}finally{if(current===sequence)loading.value=false}}
function schedule(){if(timer)clearTimeout(timer);timer=setTimeout(load,200)}
onMounted(load);onBeforeUnmount(()=>{if(timer)clearTimeout(timer)});watch([q,status,()=>route.query.hasRisk],schedule)
</script>
<template><div class="heading"><div><h1 class="title">项目</h1><p class="subtitle">所有年份的项目都在同一个长期业务档案库。</p></div><div v-if="!session.isDemo" class="actions" style="margin:0"><RouterLink to="/imports/history" class="button secondary">导入历史项目</RouterLink><RouterLink to="/projects/new" class="button primary">＋ 新建项目</RouterLink></div></div><div class="tabs"><button v-for="tab in [['ACTIVE','在办'],['COMPLETED','已完成'],['ALL','全部']]" :key="tab[0]" class="tab" :class="{active:status===tab[0]}" @click="status=tab[0]">{{tab[1]}} {{status===tab[0]?projects.length:''}}</button></div><div class="filters"><input v-model="q" class="input search-input" placeholder="搜索项目、编号或客户…" aria-label="搜索项目"/><button v-if="route.query.hasRisk" class="button mini" @click="router.push('/projects')">清除风险筛选</button></div><p v-if="loading" class="subtitle" aria-live="polite">正在刷新项目列表…</p><div v-if="error" class="empty"><p class="error">{{error}}</p><button class="button secondary" @click="load">重试</button></div><EmptyState v-else-if="!loading&&!projects.length" title="还没有符合条件的项目。" description="调整筛选条件，或建立第一个项目。"><RouterLink v-if="!session.isDemo" to="/projects/new" class="button primary">＋ 新建项目</RouterLink></EmptyState><div v-else-if="projects.length" class="table-wrap"><table class="data-table"><thead><tr><th>项目</th><th>客户</th><th>服务</th><th>负责人</th><th>下一关键节点</th><th>风险</th><th>最后复核</th></tr></thead><tbody><tr v-for="p in projects" :key="p.id" class="clickable" tabindex="0" @click="router.push(`/projects/${p.id}`)" @keyup.enter="router.push(`/projects/${p.id}`)"><td data-label="项目" style="font-size:16px;font-weight:650">{{p.name}}<small v-if="p.projectNo" class="subtitle" style="display:block;font-size:12px">{{p.projectNo}}</small></td><td data-label="客户">{{p.client?.name}}</td><td data-label="服务">{{service(p)}}</td><td data-label="负责人">{{p.owner?.name}}</td><td data-label="下一节点">{{next(p)?`${next(p).plannedDate} ${next(p).name}`:'—'}}</td><td data-label="风险"><RiskTag v-if="p.risks[0]" :level="p.risks[0].level" :text="p.risks[0].reason"/><span v-else class="subtitle">正常</span></td><td data-label="复核">{{p.lastReviewedAt.slice(0,10)}}</td></tr></tbody></table></div></template>
