<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { ApiError,get,post,session } from '../api'
const tab=ref<'employees'|'clients'>('employees'), employees=ref<any[]>([]), clients=ref<any[]>([]), name=ref(''), note=ref(''), saving=ref(false), loading=ref(false), error=ref(''), success=ref('')
async function load(){loading.value=true;error.value='';try{[employees.value,clients.value]=await Promise.all([get<any[]>('/settings/employees'),get<any[]>('/settings/clients')])}catch(e){error.value=e instanceof ApiError?e.message:'基础资料加载失败'}finally{loading.value=false}}
async function add(){if(!name.value.trim()){error.value='请填写名称';return}saving.value=true;error.value='';success.value='';try{await post(`/settings/${tab.value}`,{name:name.value,note:note.value});name.value='';note.value='';success.value='已保存';await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}finally{saving.value=false}}
onMounted(load)
</script>
<template><div><h1 class="title">设置</h1><p class="subtitle">员工仅作为项目负责人；客户和员工数据仅归属于当前账户。</p><div class="tabs"><button class="tab" :class="{active:tab==='employees'}" @click="tab='employees'">员工</button><button class="tab" :class="{active:tab==='clients'}" @click="tab='clients'">客户</button></div><section v-if="!session.isDemo" class="form-section"><h2 class="section-title">新增{{tab==='employees'?'员工':'客户'}}</h2><form class="filters" @submit.prevent="add"><input v-model.trim="name" class="input" :placeholder="tab==='employees'?'员工姓名':'客户名称'" maxlength="180" required/><input v-model="note" class="input" placeholder="备注（可选）" maxlength="1000"/><button class="button primary" :disabled="saving">{{saving?'保存中…':'新增'}}</button></form></section><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="success" class="success" role="status">{{success}}</p><p v-if="loading" class="subtitle">正在加载基础资料…</p><div v-else class="list"><div v-for="item in tab==='employees'?employees:clients" :key="item.id" class="list-row"><b>{{item.name}}</b><span class="subtitle">{{tab==='employees'?(item.active?'在职':'离职'):'客户主数据'}}</span><span class="subtitle">{{item.note}}</span></div><p v-if="!(tab==='employees'?employees:clients).length" class="subtitle">还没有{{tab==='employees'?'员工':'客户'}}。</p></div></div></template>
