import { BadRequestException, Body, Controller, Get, HttpCode, Param, Patch, Post, Query, Req, UnauthorizedException, UploadedFile, UseInterceptors } from '@nestjs/common'
import type { Request } from 'express'
import argon2 from 'argon2'
import { FileInterceptor } from '@nestjs/platform-express'
import * as XLSX from 'xlsx'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { DatabaseService } from './domain/database.service'
import { ManagerService } from './domain/manager.service'

@Controller('api/v1')
export class AppController {
  constructor(private readonly manager: ManagerService, private readonly database: DatabaseService) {}
  private user(req: Request) { const token = req.headers.authorization?.replace('Bearer ', ''); if (token !== 'local-admin-session') throw new UnauthorizedException('登录已过期'); return this.database.data().users[0] }
  @Post('auth/login') @HttpCode(200) async login(@Body() body: { username: string; password: string }) { const user = this.database.data().users.find(x => x.username === body.username); if (!user || user.disabled || user.lockedUntil && new Date(user.lockedUntil) > new Date() || !await argon2.verify(user.passwordHash, body.password || '')) { if (user) { user.failedAttempts++; if (user.failedAttempts >= 5) user.lockedUntil = new Date(Date.now() + 15 * 60_000).toISOString(); this.database.persist() } throw new UnauthorizedException('账号或密码不正确，请重新输入。') } user.failedAttempts = 0; this.database.persist(); return { token: 'local-admin-session', user: { id: user.id, username: user.username, mustChangePassword: user.mustChangePassword } } }
  @Get('auth/me') me(@Req() req: Request) { const user = this.user(req); return { id: user.id, username: user.username, mustChangePassword: user.mustChangePassword } }
  @Post('auth/change-password') async changePassword(@Req() req: Request, @Body() body: { password: string }) { const user = this.user(req); if (!body.password || body.password.length < 12) throw new UnauthorizedException('密码至少需要 12 位'); user.passwordHash = await argon2.hash(body.password, { type: argon2.argon2id }); user.mustChangePassword = false; this.database.audit('CHANGE_PASSWORD', 'User', user.id); return { ok: true } }
  @Get('dashboard') dashboard(@Req() req: Request) { this.user(req); return this.manager.dashboard() }
  @Get('projects') projects(@Req() req: Request, @Query() query: Record<string, string>) { this.user(req); return this.manager.list(query) }
  @Post('projects') createProject(@Req() req: Request, @Body() body: any) { this.user(req); return this.manager.create(body) }
  @Get('projects/:id') project(@Req() req: Request, @Param('id') id: string) { this.user(req); return this.manager.get(id) }
  @Patch('projects/:id') updateProject(@Req() req: Request, @Param('id') id: string, @Body() body: any) { this.user(req); return this.manager.update(id, body) }
  @Post('projects/:id/quick-update') quickUpdate(@Req() req: Request, @Param('id') id: string, @Body() body: any) { this.user(req); return this.manager.quickUpdate(id, body) }
  @Get('finance/overview') financeOverview(@Req() req: Request, @Query() query: Record<string, string>) { this.user(req); return this.manager.financeOverview(query) }
  @Get('finance/projects') financeProjects(@Req() req: Request, @Query() query: Record<string, string>) { this.user(req); return this.manager.finance(query) }
  @Post('finance/:type') recordFinance(@Req() req: Request, @Param('type') type: string, @Body() body: any) { this.user(req); return this.manager.recordFinance(type, body) }
  @Get('settings/employees') employees(@Req() req: Request) { this.user(req); return this.database.data().employees }
  @Post('settings/employees') employee(@Req() req: Request, @Body() body: any) { this.user(req); if (!body.name?.trim()) throw new UnauthorizedException('姓名不能为空'); const item = { id: crypto.randomUUID(), name: body.name.trim(), active: body.active !== false, note: body.note }; this.database.data().employees.push(item); this.database.audit('CREATE', 'Employee', item.id, undefined, item); return item }
  @Get('settings/clients') clients(@Req() req: Request) { this.user(req); return this.database.data().clients }
  @Post('settings/clients') client(@Req() req: Request, @Body() body: any) { this.user(req); if (!body.name?.trim()) throw new UnauthorizedException('客户名称不能为空'); const item = { id: crypto.randomUUID(), name: body.name.trim(), note: body.note }; this.database.data().clients.push(item); this.database.audit('CREATE', 'Client', item.id, undefined, item); return item }
  @Get('search') search(@Req() req: Request, @Query('q') q = '') { this.user(req); const projects = this.manager.list({ q }); const lower = q.toLowerCase(); const documents = this.database.data().documents.filter(d => !d.hidden && (d.title.toLowerCase().includes(lower) || d.originalName.toLowerCase().includes(lower))).map(d => ({ ...d, project: this.database.data().projects.find(p => p.id === d.projectId)?.name })); return { projects, documents } }
  @Post('imports/history/preview') @UseInterceptors(FileInterceptor('file')) previewImport(@Req() req: Request, @UploadedFile() file?: Express.Multer.File) { this.user(req); if (!file) throw new BadRequestException('请选择 Excel 文件'); if (!/\.(xlsx|xls)$/i.test(file.originalname)) throw new BadRequestException('仅支持 .xlsx 或 .xls 文件'); const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(XLSX.read(file.buffer, { type: 'buffer' }).Sheets[XLSX.read(file.buffer, { type: 'buffer' }).SheetNames[0]], { defval: '' }); const required = ['项目名称*', '客户*', '年份*', '服务类型*', '状态*']; const errors = rows.flatMap((row, index) => required.filter(key => !String(row[key] || '').trim()).map(key => ({ row: index + 2, message: `${key} 不能为空` }))); const db = this.database.data(); const valid = rows.filter((_, index) => !errors.some(e => e.row === index + 2)); const duplicates = valid.filter(row => db.projects.some(p => p.name === String(row['项目名称*']).trim() && p.businessYear === Number(row['年份*']))).length; const batch = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), originalName: file.originalname, rows, errors, validCount: valid.length - duplicates, duplicateCount: duplicates, status: 'PREVIEW' }; const data = db as any; data.batches ||= []; data.batches.unshift(batch); mkdirSync(join(process.cwd(), 'uploads', 'imports'), { recursive: true }); writeFileSync(join(process.cwd(), 'uploads', 'imports', `${batch.id}-${file.originalname}`), file.buffer); this.database.persist(); return { id: batch.id, total: rows.length, validCount: batch.validCount, duplicateCount: duplicates, errors } }
  @Post('imports/history/:id/confirm') confirmImport(@Req() req: Request, @Param('id') id: string) { this.user(req); const data = this.database.data() as any; const batch = (data.batches || []).find((b: any) => b.id === id); if (!batch) throw new BadRequestException('导入批次不存在'); if (batch.status !== 'PREVIEW') throw new BadRequestException('该批次已处理'); if (batch.errors.length) throw new BadRequestException('请先修正所有阻断错误'); let created = 0; for (const row of batch.rows) { const name = String(row['项目名称*']).trim(), year = Number(row['年份*']); if (data.projects.some((p: any) => p.name === name && p.businessYear === year)) continue; const clientName = String(row['客户*']).trim(); let client = data.clients.find((c: any) => c.name === clientName); if (!client) { client = { id: crypto.randomUUID(), name: clientName }; data.clients.push(client) } const owner = data.employees.find((e: any) => e.name === String(row['负责人'] || '').trim()) || data.employees[0]; const serviceMap: any = { '招标代理': 'BIDDING', '造价/预结算': 'COST', '监理': 'SUPERVISION', '其他': 'OTHER' }; const statusMap: any = { '在办': 'ACTIVE', '已完成': 'COMPLETED', '已取消': 'CANCELLED' }; this.manager.create({ name, projectNo: String(row['项目编号'] || '') || undefined, clientId: client.id, businessYear: year, ownerId: owner.id, status: statusMap[String(row['状态*'])] || 'ACTIVE', startDate: String(row['开始日期'] || '') || undefined, plannedEndDate: String(row['计划完成日期'] || '') || undefined, actualEndDate: String(row['实际完成日期'] || '') || undefined, targetAmount: Number(row['项目/采购标的金额'] || 0) || undefined, note: String(row['备注'] || '') || undefined, services: [{ id: crypto.randomUUID(), serviceType: serviceMap[String(row['服务类型*'])] || 'OTHER', stage: '历史导入', ownerId: owner.id, otherDescription: serviceMap[String(row['服务类型*'])] ? undefined : String(row['服务类型*']) }] } as any); created++ } batch.status = 'IMPORTED'; batch.importedCount = created; this.database.audit('IMPORT', 'ImportBatch', id, undefined, { created }); return { created } }
}
