import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common'
import type { Contract, Project, Risk, ServiceType } from '../../shared/domain'
import { DatabaseService } from './database.service'

const today = () => new Date().toISOString().slice(0, 10)
const dayDiff = (date: string) => Math.floor((new Date(`${today()}T00:00:00`).getTime() - new Date(`${date}T00:00:00`).getTime()) / 86400000)
const sum = (items: Array<{ amount: number }>) => items.reduce((total, item) => total + Number(item.amount), 0)

@Injectable()
export class ManagerService {
  constructor(private readonly database: DatabaseService) {}
  private db() { return this.database.data() }
  private project(id: string) { const item = this.db().projects.find(p => p.id === id); if (!item) throw new NotFoundException('项目不存在'); return item }
  enrich(project: Project) { const db = this.db(); const owner = db.employees.find(e => e.id === project.ownerId); const client = db.clients.find(c => c.id === project.clientId); const contracts = db.contracts.filter(c => c.projectId === project.id && !c.void); const contractIds = contracts.map(c => c.id); const invoices = db.invoices.filter(i => contractIds.includes(i.contractId) && !i.void); const payments = db.payments.filter(p => contractIds.includes(p.contractId) && !p.void); return { ...project, owner, client, contracts, invoices, payments, finance: { contractAmount: sum(contracts), invoiceAmount: sum(invoices), paymentAmount: sum(payments), receivableAmount: sum(contracts) - sum(payments) } } }
  risks(project: Project): Risk[] { if (project.status === 'CANCELLED') return []; const owner = this.db().employees.find(e => e.id === project.ownerId)?.name || '未分配'; const risks: Risk[] = []
    if (project.status === 'ACTIVE') { for (const m of project.milestones.filter(x => !x.actualDate)) { const diff = dayDiff(m.plannedDate); if (diff > 0 && m.critical) risks.push({ projectId: project.id, projectName: project.name, owner, reason: `关键节点“${m.name}”已延期 ${diff} 天`, level: 'danger', days: diff }); if (diff <= 0 && diff >= -7) risks.push({ projectId: project.id, projectName: project.name, owner, reason: `关键节点“${m.name}”${Math.abs(diff)} 天后到期`, level: 'warning', days: Math.abs(diff) }) }
      const unreviewed = dayDiff(project.lastReviewedAt.slice(0, 10)); if (unreviewed >= 14) risks.push({ projectId: project.id, projectName: project.name, owner, reason: `${unreviewed} 日未复核`, level: 'warning', days: unreviewed })
      for (const issue of project.issues.filter(i => i.status !== 'CLOSED')) { const diff = dayDiff(issue.dueDate); if (diff > 0) risks.push({ projectId: project.id, projectName: project.name, owner, reason: `监理问题“${issue.title}”整改逾期 ${diff} 天`, level: 'danger', days: diff }) }
    }
    const contracts = this.db().contracts.filter(c => c.projectId === project.id && !c.void); for (const contract of contracts) { const paid = sum(this.db().payments.filter(p => p.contractId === contract.id && !p.void)); if (contract.expectedPaymentDate && contract.amount > paid && dayDiff(contract.expectedPaymentDate) > 0) risks.push({ projectId: project.id, projectName: project.name, owner, reason: `应收 ¥${(contract.amount - paid).toLocaleString()} 逾期 ${dayDiff(contract.expectedPaymentDate)} 天`, level: 'danger', days: dayDiff(contract.expectedPaymentDate) }) }
    return risks
  }
  list(query: Record<string, string>) { let items = this.db().projects; if (query.status) items = items.filter(p => p.status === query.status); if (query.businessYear) items = items.filter(p => p.businessYear === Number(query.businessYear)); if (query.clientId) items = items.filter(p => p.clientId === query.clientId); if (query.ownerId) items = items.filter(p => p.ownerId === query.ownerId); if (query.serviceType) items = items.filter(p => p.services.some(s => s.serviceType === query.serviceType)); if (query.hasRisk === 'true') items = items.filter(p => this.risks(p).length > 0); if (query.q) { const q = query.q.toLowerCase(); items = items.filter(p => p.name.toLowerCase().includes(q) || p.projectNo?.toLowerCase().includes(q) || this.db().clients.find(c => c.id === p.clientId)?.name.toLowerCase().includes(q)) } return items.map(p => ({ ...this.enrich(p), risks: this.risks(p) })) }
  get(id: string) { const project = this.project(id); return { ...this.enrich(project), risks: this.risks(project), documents: this.db().documents.filter(d => d.projectId === id && !d.hidden), audit: this.db().audit.filter(a => a.entityId === id).slice(0, 30) } }
  create(input: Partial<Project>) { if (!input.name || !input.clientId || !input.ownerId || !input.status || !input.services?.length) throw new BadRequestException('项目名称、客户、服务类型、负责人和状态为必填项'); if (input.services.some(s => s.serviceType === 'OTHER' && !s.otherDescription?.trim())) throw new BadRequestException('“其他”服务必须填写服务说明'); const now = new Date().toISOString(); const project: Project = { id: crypto.randomUUID(), name: input.name.trim(), projectNo: input.projectNo, clientId: input.clientId, businessYear: input.businessYear || new Date().getFullYear(), ownerId: input.ownerId, status: input.status, startDate: input.startDate, plannedEndDate: input.plannedEndDate, actualEndDate: input.actualEndDate, targetAmount: input.targetAmount, note: input.note, lastReviewedAt: now, createdAt: now, updatedAt: now, services: input.services.map(s => ({ ...s, id: s.id || crypto.randomUUID() })), milestones: input.milestones || [], costResults: input.costResults || [], issues: input.issues || [] }; this.db().projects.unshift(project); this.database.audit('CREATE', 'Project', project.id, undefined, project); return this.get(project.id) }
  update(id: string, input: Partial<Project>) { const project = this.project(id); const before = structuredClone(project); Object.assign(project, input, { id, updatedAt: new Date().toISOString() }); if (input.services?.some(s => s.serviceType === 'OTHER' && !s.otherDescription?.trim())) throw new BadRequestException('“其他”服务必须填写服务说明'); this.database.audit('UPDATE', 'Project', id, before, project); return this.get(id) }
  quickUpdate(id: string, input: { status?: Project['status']; services?: Project['services']; nextMilestone?: { name: string; plannedDate: string; serviceId?: string }; note?: string }) { const project = this.project(id); const before = structuredClone(project); if (input.status) project.status = input.status; if (input.services) project.services = input.services; if (input.nextMilestone?.name && input.nextMilestone.plannedDate) { const incomplete = project.milestones.find(m => !m.actualDate); if (incomplete) Object.assign(incomplete, input.nextMilestone); else project.milestones.push({ id: crypto.randomUUID(), ...input.nextMilestone, critical: true }) } if (input.note) project.note = input.note; project.lastReviewedAt = new Date().toISOString(); project.updatedAt = project.lastReviewedAt; this.database.audit('QUICK_UPDATE', 'Project', id, before, project); return this.get(id) }
  dashboard() { const active = this.db().projects.filter(p => p.status === 'ACTIVE'); const risks = this.db().projects.flatMap(p => this.risks(p)).sort((a, b) => (a.level === b.level ? b.days - a.days : a.level === 'danger' ? -1 : 1)); const all = this.finance({}); const upcoming = active.flatMap(p => p.milestones.filter(m => !m.actualDate && dayDiff(m.plannedDate) <= 0 && dayDiff(m.plannedDate) >= -14).map(m => ({ ...m, projectId: p.id, projectName: p.name }))).sort((a, b) => a.plannedDate.localeCompare(b.plannedDate)); const month = new Date().toISOString().slice(0, 7); const monthPayment = sum(this.db().payments.filter(p => !p.void && p.paymentDate.startsWith(month))); return { activeCount: active.length, attentionCount: new Set(risks.map(r => r.projectId)).size, receivableAmount: all.receivableAmount, monthPaymentAmount: monthPayment, risks: risks.slice(0, 8), upcoming, recentProjects: active.slice(0, 6).map(p => this.enrich(p)) } }
  finance(query: Record<string, string>) { let projects = this.db().projects; if (query.businessYear) projects = projects.filter(p => p.businessYear === Number(query.businessYear)); if (query.clientId) projects = projects.filter(p => p.clientId === query.clientId); if (query.serviceType) projects = projects.filter(p => p.services.some(s => s.serviceType === query.serviceType)); if (query.completed === 'true') projects = projects.filter(p => p.status === 'COMPLETED'); if (query.completed === 'false') projects = projects.filter(p => p.status !== 'COMPLETED'); const rows = projects.map(p => this.enrich(p)); const contractAmount = rows.reduce((x, p) => x + p.finance.contractAmount, 0); const invoiceAmount = rows.reduce((x, p) => x + p.finance.invoiceAmount, 0); const paymentAmount = rows.reduce((x, p) => x + p.finance.paymentAmount, 0); const overdue = projects.reduce((x, p) => x + this.db().contracts.filter(c => c.projectId === p.id && !c.void && c.expectedPaymentDate && dayDiff(c.expectedPaymentDate) > 0).reduce((s, c) => s + Math.max(0, c.amount - sum(this.db().payments.filter(pay => pay.contractId === c.id && !pay.void))), 0), 0); return { projects: rows.map(p => ({ ...p, risks: this.risks(p) })), projectCount: rows.length, contractAmount, invoiceAmount, paymentAmount, receivableAmount: contractAmount - paymentAmount, overdueAmount: overdue }
  }
  financeOverview(query: Record<string, string>) { const base = this.finance(query); const groupBy = query.groupBy; if (!groupBy || groupBy === 'project') return { ...base, groups: [] }; const groups = new Map<string, { key: string; label: string; ids: Set<string> }>(); for (const item of base.projects) { const values = groupBy === 'businessYear' ? [{ key: String(item.businessYear), label: String(item.businessYear) }] : groupBy === 'client' ? [{ key: item.clientId, label: item.client?.name || '未知客户' }] : item.services.map(s => ({ key: s.serviceType, label: ({ BIDDING: '招标代理', COST: '造价/预结算', SUPERVISION: '监理', OTHER: '其他' } as Record<ServiceType,string>)[s.serviceType] })); for (const v of values) { if (!groups.has(v.key)) groups.set(v.key, { ...v, ids: new Set() }); groups.get(v.key)!.ids.add(item.id) } }
    return { ...base, groups: [...groups.values()].map(g => { const data = this.finance({ ...query, groupBy: '', ...(groupBy === 'businessYear' ? { businessYear: g.key } : groupBy === 'client' ? { clientId: g.key } : { serviceType: g.key }) }); return { key: g.key, label: g.label, projectCount: g.ids.size, contractAmount: data.contractAmount, invoiceAmount: data.invoiceAmount, paymentAmount: data.paymentAmount, receivableAmount: data.receivableAmount } }), serviceTypeOverlap: groupBy === 'serviceType' }
  }
  recordFinance(type: string, input: Record<string, unknown>) { const db = this.db(); if (type === 'contract') { if (!input.projectId || !input.contractNo || !input.amount) throw new BadRequestException('请完整填写合同信息'); const item: Contract = { id: crypto.randomUUID(), projectId: String(input.projectId), contractNo: String(input.contractNo), amount: Number(input.amount), signedDate: input.signedDate ? String(input.signedDate) : undefined, expectedPaymentDate: input.expectedPaymentDate ? String(input.expectedPaymentDate) : undefined, note: input.note ? String(input.note) : undefined }; db.contracts.unshift(item); this.database.audit('CREATE', 'Contract', item.id, undefined, item); return item }
    if (type === 'invoice') { if (!input.contractId || !input.invoiceNo || !input.amount || !input.invoiceDate) throw new BadRequestException('请完整填写发票信息'); const item = { id: crypto.randomUUID(), contractId: String(input.contractId), invoiceNo: String(input.invoiceNo), amount: Number(input.amount), invoiceDate: String(input.invoiceDate), note: input.note ? String(input.note) : undefined }; db.invoices.unshift(item); this.database.audit('CREATE', 'Invoice', item.id, undefined, item); return item }
    if (type === 'payment') { if (!input.contractId || !input.amount || !input.paymentDate) throw new BadRequestException('请完整填写回款信息'); const item = { id: crypto.randomUUID(), contractId: String(input.contractId), amount: Number(input.amount), paymentDate: String(input.paymentDate), note: input.note ? String(input.note) : undefined }; db.payments.unshift(item); this.database.audit('CREATE', 'Payment', item.id, undefined, item); return item }
    throw new BadRequestException('未知经营记录类型')
  }
}
