CREATE TYPE "UserRole" AS ENUM ('DEMO', 'USER');
CREATE TYPE "ProjectStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED');
CREATE TYPE "ServiceType" AS ENUM ('BIDDING', 'COST', 'SUPERVISION', 'OTHER');
CREATE TYPE "ImportStatus" AS ENUM ('PREVIEW', 'IMPORTED', 'EXPIRED');

CREATE TABLE "User" ("id" UUID PRIMARY KEY, "username" VARCHAR(64) NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "role" "UserRole" NOT NULL DEFAULT 'USER', "disabledAt" TIMESTAMP(3), "failedAttempts" INTEGER NOT NULL DEFAULT 0, "lockedUntil" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Session" ("id" UUID PRIMARY KEY, "tokenHash" CHAR(64) NOT NULL UNIQUE, "userId" UUID NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Employee" ("id" UUID PRIMARY KEY, "userId" UUID NOT NULL, "name" VARCHAR(120) NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "note" VARCHAR(1000), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE ("userId", "name"));
CREATE TABLE "Client" ("id" UUID PRIMARY KEY, "userId" UUID NOT NULL, "name" VARCHAR(180) NOT NULL, "note" VARCHAR(1000), "disabled" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE ("userId", "name"));
CREATE TABLE "Project" ("id" UUID PRIMARY KEY, "userId" UUID NOT NULL, "name" VARCHAR(240) NOT NULL, "projectNo" VARCHAR(100), "clientId" UUID NOT NULL, "ownerId" UUID NOT NULL, "businessYear" INTEGER NOT NULL, "status" "ProjectStatus" NOT NULL, "startDate" DATE, "plannedEndDate" DATE, "actualEndDate" DATE, "targetAmount" DECIMAL(18,2), "note" VARCHAR(4000), "lastReviewedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE ("userId", "projectNo"));
CREATE TABLE "ProjectService" ("id" UUID PRIMARY KEY, "projectId" UUID NOT NULL, "ownerId" UUID NOT NULL, "serviceType" "ServiceType" NOT NULL, "stage" VARCHAR(160) NOT NULL, "otherDescription" VARCHAR(500), "plannedEndDate" DATE, "actualEndDate" DATE, "note" VARCHAR(2000));
CREATE TABLE "Milestone" ("id" UUID PRIMARY KEY, "projectId" UUID NOT NULL, "serviceId" UUID, "name" VARCHAR(240) NOT NULL, "plannedDate" DATE NOT NULL, "actualDate" DATE, "critical" BOOLEAN NOT NULL DEFAULT false, "note" VARCHAR(2000));
CREATE TABLE "Contract" ("id" UUID PRIMARY KEY, "projectId" UUID NOT NULL, "contractNo" VARCHAR(120) NOT NULL, "amount" DECIMAL(18,2) NOT NULL, "signedDate" DATE, "expectedPaymentDate" DATE, "note" VARCHAR(2000), "void" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE ("projectId", "contractNo"));
CREATE TABLE "Invoice" ("id" UUID PRIMARY KEY, "contractId" UUID NOT NULL, "invoiceNo" VARCHAR(120) NOT NULL, "invoiceDate" DATE NOT NULL, "amount" DECIMAL(18,2) NOT NULL, "note" VARCHAR(2000), "void" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("contractId", "invoiceNo"));
CREATE TABLE "Payment" ("id" UUID PRIMARY KEY, "contractId" UUID NOT NULL, "paymentDate" DATE NOT NULL, "amount" DECIMAL(18,2) NOT NULL, "note" VARCHAR(2000), "void" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Document" ("id" UUID PRIMARY KEY, "projectId" UUID NOT NULL, "category" VARCHAR(32) NOT NULL, "title" VARCHAR(240) NOT NULL, "originalName" VARCHAR(255) NOT NULL, "mimeType" VARCHAR(120) NOT NULL, "size" INTEGER NOT NULL, "objectKey" VARCHAR(512) NOT NULL UNIQUE, "checksum" CHAR(64), "isFinal" BOOLEAN NOT NULL DEFAULT false, "hidden" BOOLEAN NOT NULL DEFAULT false, "note" VARCHAR(2000), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ImportBatch" ("id" UUID PRIMARY KEY, "userId" UUID NOT NULL, "originalName" VARCHAR(255) NOT NULL, "objectKey" VARCHAR(512) NOT NULL UNIQUE, "rowsJson" JSONB NOT NULL, "errorsJson" JSONB NOT NULL, "status" "ImportStatus" NOT NULL DEFAULT 'PREVIEW', "total" INTEGER NOT NULL, "validCount" INTEGER NOT NULL, "duplicateCount" INTEGER NOT NULL, "importedCount" INTEGER, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuditEvent" ("id" UUID PRIMARY KEY, "userId" UUID, "action" VARCHAR(80) NOT NULL, "entityType" VARCHAR(80) NOT NULL, "entityId" VARCHAR(80) NOT NULL, "beforeJson" JSONB, "afterJson" JSONB, "ip" VARCHAR(64), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Client" ADD CONSTRAINT "Client_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE RESTRICT;
ALTER TABLE "Project" ADD CONSTRAINT "Project_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "Employee"("id") ON DELETE RESTRICT;
ALTER TABLE "ProjectService" ADD CONSTRAINT "ProjectService_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE;
ALTER TABLE "ProjectService" ADD CONSTRAINT "ProjectService_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "Employee"("id") ON DELETE RESTRICT;
ALTER TABLE "Milestone" ADD CONSTRAINT "Milestone_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE;
ALTER TABLE "Milestone" ADD CONSTRAINT "Milestone_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "ProjectService"("id") ON DELETE SET NULL;
ALTER TABLE "Contract" ADD CONSTRAINT "Contract_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_contractId_fkey" FOREIGN KEY ("contractId") REFERENCES "Contract"("id") ON DELETE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_contractId_fkey" FOREIGN KEY ("contractId") REFERENCES "Contract"("id") ON DELETE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE;
ALTER TABLE "ImportBatch" ADD CONSTRAINT "ImportBatch_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL;

CREATE INDEX "Session_userId_expiresAt_idx" ON "Session"("userId", "expiresAt");
CREATE INDEX "Employee_userId_active_idx" ON "Employee"("userId", "active");
CREATE INDEX "Client_userId_disabled_idx" ON "Client"("userId", "disabled");
CREATE INDEX "Project_userId_businessYear_status_idx" ON "Project"("userId", "businessYear", "status");
CREATE INDEX "Project_userId_clientId_idx" ON "Project"("userId", "clientId");
CREATE INDEX "ProjectService_projectId_serviceType_idx" ON "ProjectService"("projectId", "serviceType");
CREATE INDEX "Milestone_projectId_plannedDate_idx" ON "Milestone"("projectId", "plannedDate");
CREATE INDEX "Contract_projectId_void_idx" ON "Contract"("projectId", "void");
CREATE INDEX "Invoice_contractId_void_idx" ON "Invoice"("contractId", "void");
CREATE INDEX "Payment_contractId_void_idx" ON "Payment"("contractId", "void");
CREATE INDEX "Document_projectId_hidden_idx" ON "Document"("projectId", "hidden");
CREATE INDEX "ImportBatch_userId_status_expiresAt_idx" ON "ImportBatch"("userId", "status", "expiresAt");
CREATE INDEX "AuditEvent_userId_createdAt_idx" ON "AuditEvent"("userId", "createdAt");
CREATE INDEX "AuditEvent_entityType_entityId_createdAt_idx" ON "AuditEvent"("entityType", "entityId", "createdAt");
